### ISSUE TITLE
Postcode doesn't show in the letter/PDF

### ISSUE THREAD

**Issue by postdigital** [DataRights/MAPPED#49]
For some reason the postcode is not displayed in the address appearing on the letter.

**Comment by mani47** [comment]
Because you have not defined it correctly in the admin panel.

Instead of:

`[[organisation postal_code]]`

it should be:

`{{organization.address.post_code}}`

please note that smallest error in the format causes an invalid liquid parse and empty space. in this case, there were 4 mistakes:

1- Instead of [[ you should use {{
2- "Organisation" should be "Organization" 
3- the postal code is inside address object so instead of "Organization.postal_code" it should be "organization.address.post_code".
4- In database name of the field is "post_code" not "postal_code".
